version: '3.8'

services:

    apisix:
        image: apache/apisix:latest
        container_name: apisix-standalone-microservices
        volumes:
            - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
            - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
        ports:
            - "9000:9000"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    kafka:
        image: confluentinc/cp-kafka:latest
        hostname: kafka
        container_name: kafka 
        ports:
            - "9092:9092" 
        environment:
            KAFKA_KRAFT_MODE: 'true'
            KAFKA_PROCESS_ROLES: controller,broker 
            KAFKA_NODE_ID: 1

            # Interne Controller-Kommunikation
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

            # Critical changes: Listeners configuration
            # Define listeners for broker, controller, and internal communication
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
            
            # The advertised listeners for clients to connect to the broker and for inter-broker communication
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092

            # Listener security protocol map, it maps listener names to security protocols
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT

            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

            # Other configs
            KAFKA_LOG_DIRS: /var/lib/kafka/data 
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
            KAFKA_LOG_RETENTION_HOURS: 1
            KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"