spring:
  application:
    name: identity
  profiles:
    active: ${ENVIRONMENT:development}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway: 
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

swagger:
  base-path: /**
springdoc:
  swagger-ui:
    path: /api/docs
    doc-expansion: none
  api.version: ${api.version}

server:
  port: 5000

frontend:
  port: 4200

security:
  jwt:
    secret: ${JWT_KEY}
    expiration: ${JWT_EXPIRATION:3600}
    alg: ${JWT_ALG:HS256}

app:
  default-role: CLIENT
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
